services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TARGETAPP=bot
    restart: no
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=kiasuo
      - POSTGRES_USER=kiasuo
      - POSTGRES_PASSWORD=kiasuo
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    user: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=kiasuo
      - POSTGRES_USER=kiasuo
      - POSTGRES_PASSWORD=kiasuo
    env_file:
      - .env
    expose:
      - 5432
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "kiasuo", "-U", "kiasuo"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:alpine
    restart: unless-stopped
    command: --save 60 10
    volumes:
      - redis-data:/data
    expose:
      - 6379
    ports:
      - "127.0.0.1:6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres-data:
  redis-data:
