services:
  app:
    image: ${APP_IMAGE_REF}
    restart: always
    volumes:
      - redis-socket:/run/redis-socket
    environment:
      - REDIS_URL=unix://redis/run/redis-socket/redis.sock
      - WORKER_AUTH=${WORKER_AUTH}
      - ADMIN_ID=${ADMIN_ID}
      - TELEGRAM_TOKEN_FILE=/run/secrets/kiasuo-telegram
      - CRYPTO_SECRET_FILE=/run/secrets/kiasuo-crypto
      - HTTP_TELEGRAM_TOKEN_FILE=/run/secrets/kiasuo-http-telegram
    secrets:
      - kiasuo-telegram
      - kiasuo-crypto
      - kiasuo-http-telegram
    expose:
      - 39814
    ports:
      - "127.0.0.1:39814:39814"
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      replicas: 1
  redis:
    image: redis:alpine
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - redis-data:/data
      - redis-socket:/run/redis-socket
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "-s", "/run/redis-socket/redis.sock", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      replicas: 1
secrets:
  kiasuo-telegram:
    external: true
  kiasuo-http-telegram:
    external: true
  kiasuo-crypto:
    external: true
volumes:
  redis-data:
  redis-socket:
