services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TARGETAPP=app
    restart: no
    environment:
      - REDIS_URL=redis://redis
    env_file:
      - .env
    expose:
      - 39814
    ports:
      - "127.0.0.1:39814:39814"
    depends_on:
      redis:
        condition: service_healthy
  redis:
    image: redis:alpine
    restart: unless-stopped
    command: --save 60 1
    volumes:
      - redis-data:/data
    expose:
      - 6379
    ports:
      - "127.0.0.1:6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  redis-data:
