services:
  telegram:
    image: ${TELEGRAM_IMAGE_REF}
    environment:
      - TELEGRAM_FILE=/run/secrets/telegram
      - CRYPTO_FILE=/run/secrets/crypto
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=kiasuo
      - POSTGRES_USER=kiasuo
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres
    secrets:
      - telegram
      - crypto
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
  discord:
    image: ${DISCORD_IMAGE_REF}
    restart: always
    environment:
      - DISCORD_FILE=/run/secrets/discord
      - CRYPTO_FILE=/run/secrets/crypto
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=kiasuo
      - POSTGRES_USER=kiasuo
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres
    secrets:
      - discord
      - crypto
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:alpine
    restart: always
    user: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=kiasuo
      - POSTGRES_USER=kiasuo
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres
    secrets:
      - postgres
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "kiasuo", "-U", "kiasuo"]
      interval: 10s
      timeout: 5s
      retries: 5
secrets:
  telegram:
    file: ~/.kiasuo-secrets/telegram.txt
  discord:
    file: ~/.kiasuo-secrets/discord.txt
  crypto:
    file: ~/.kiasuo-secrets/crypto.txt
  postgres:
    file: ~/.kiasuo-secrets/postgres.txt
volumes:
  postgres-data:
