services:
  bot:
    image: ${BOT_IMAGE_REF}
    restart: always
    volumes:
      - postgres-socket:/var/run/postgresql
    environment:
      - TELEGRAM_FILE=/run/secrets/telegram
      - CRYPTO_FILE=/run/secrets/crypto
      - POSTGRES_HOST=/var/run/postgresql
      - POSTGRES_DB=kiasuo
      - POSTGRES_USER=kiasuo
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres
      - WORKER_AUTH=${WORKER_AUTH}
    secrets:
      - telegram
      - crypto
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:16-alpine
    command: "postgres -c listen_addresses="
    restart: always
    user: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-socket:/var/run/postgresql
    environment:
      - POSTGRES_DB=kiasuo
      - POSTGRES_USER=kiasuo
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres
    secrets:
      - postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "kiasuo", "-U", "kiasuo"]
      interval: 10s
      timeout: 5s
      retries: 5
secrets:
  telegram:
    file: /home/kiasuo/.secrets/telegram.txt
  crypto:
    file: /home/kiasuo/.secrets/crypto.txt
  postgres:
    file: /home/kiasuo/.secrets/postgres.txt
volumes:
  postgres-data:
  postgres-socket:
