services:
  app:
    image: ${APP_IMAGE_REF}
    restart: always
    volumes:
      - redis-socket:/run/redis-socket
    environment:
      - REDIS_URL=unix://redis/run/redis-socket/redis.sock
      - WORKER_AUTH=${WORKER_AUTH}
      - ADMIN_ID=${ADMIN_ID}
      - TELEGRAM_TOKEN_FILE=/run/secrets/kiasuo-telegram
      - CRYPTO_SECRET_FILE=/run/secrets/kiasuo-crypto
      - HTTP_TELEGRAM_TOKEN_FILE=/run/secrets/kiasuo-http-telegram
    secrets:
      - kiasuo-telegram
      - kiasuo-crypto
      - kiasuo-http-telegram
    ports:
      - "127.0.0.1:39814:39814"
    depends_on:
      - redis
    deploy:
      mode: global
      resources:
        limits:
          memory: 256MB
  redis:
    image: redis:alpine
    restart: unless-stopped
    command: >
      sh -c "mkdir -p /run/redis-socket && chown -R redis:redis /run/redis-socket &&
             exec redis-server --loglevel warning --unixsocket /run/redis-socket/redis.sock --unixsocketperm 777 --port 0 --save 60 1"
    volumes:
      - redis-data:/data
      - redis-socket:/run/redis-socket
    healthcheck:
      test: ["CMD", "redis-cli", "-s", "/run/redis-socket/redis.sock", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      mode: global
secrets:
  kiasuo-telegram:
    external: true
  kiasuo-http-telegram:
    external: true
  kiasuo-crypto:
    external: true
volumes:
  redis-data:
  redis-socket:
