services:
  app:
    image: ${APP_IMAGE_REF}
    restart: always
    volumes:
      - redis-socket:/run/redis-socket
    environment:
      - REDIS_URL=unix://redis/run/redis-socket/redis.sock
      - TELEGRAM_TOKEN_FILE=/run/secrets/telegram
      - CRYPTO_SECRET_FILE=/run/secrets/crypto
      - WORKER_AUTH=${WORKER_AUTH}
      - ADMIN_ID=${ADMIN_ID}
    expose:
      - 39814
    ports:
      - "127.0.0.1:39814:39814"
    secrets:
      - telegram
      - crypto
    depends_on:
      redis:
        condition: service_healthy
  redis:
    image: redis:alpine
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - redis-data:/data
      - redis-socket:/run/redis-socket
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    healthcheck:
      test: ["CMD", "redis-cli", "-s", "/run/redis-socket/redis.sock", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
secrets:
  telegram:
    file: /home/kiasuo/.secrets/telegram.txt
  crypto:
    file: /home/kiasuo/.secrets/crypto.txt
volumes:
  redis-data:
  redis-socket:
