name: Deploy worker

on:
  push:
    branches: [master]
    paths: ["**/*.ts", "**/*.json", "wrangler.toml", ".github/workflows/deploy-worker.yml"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
