name: Deploy commands

on:
  push:
    branches: [master]
    paths: ["scripts/deploy-commands.sh", ".github/workflows/deploy-commands.yml"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          sparse-checkout: "scripts/deploy-commands.sh"
          sparse-checkout-cone-mode: false
      - name: Deploy commands
        run: scripts/deploy-commands.sh
        env:
          DISCORD: ${{ secrets.DISCORD }}
