name: Test

on:
  push:
    branches: [master]
    paths: ["**/*.go", "go.mod", "go.sum", "Dockerfile", ".github/workflows/test.yml", ".github/workflows/publish-docker.yml"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.6"
      - name: Test
        run: go test -v ./...
